### PR TITLE
Sidebar for pokemon info

### PR DESCRIPTION
**Pull request by Eruyome**
Sidebar shows enemy and ally pokemon cards, all at the same time.
Sidebar can be toggled on/off in the settings menu.
Sidebar can be positioned left or right off the the game app, can be set in the options menu.
Showing/hiding enemy or ally party in theoptions menu also affects what's being displayed in the sidebar.
While the sidebar is enabled/shown, the overlay enemy and ally pokemon cards are hidden via css classes.

### CODE REVIEW

**Comment by sirzento** [comment]
That's actually exactly what I am looking for. Would be nice if there would also be an on/off option for showing the IV's or hide them

**Comment by Eruyome** [comment]
I'll look into it. I didn't want to cram too many options into the options menu (for now). With too many options we'll probably have to change its scale or add scrollbars. 
Maybe I can just add a button directly onto the sidebar to show/hide them, but that would reset every time you reload the page, which also doesn't sit right with me. It's not like I couldn't make it persistent, but it would be inconsistent to have persistent settings outside of the options menu.

Anyways, you'll at least not see the ivs in battles involving more than 8 pokemon. Even though I don't like the current condensed version. Could do something nicer by using a different html structure instead of reusing the normal one and forcing it to be something different purely with css.
roguedex

**Comment by sirzento** [comment]
If you don't like the condensed view, maybe you could only condense the info from your own team and still show the full info from the enemy since you don't really need to know your IV's and abilities all the time when battling with other trainers.

Also, if you have a big screen it would be a good idea to give the user an option to not compakt the view if 9+ Pokemons are in the round to still let them see everything if the space is available.

**Comment by sirzento** [comment]
@Eruyome I can't create an issue on your fork but I saw that the type icons don't get bigger if you increase the sidebar scale.

On 1.0x you can see how good the icon fits into the bar:
grafik

On 1.5x you can see that the icons still have the exact same size as 1.0x. The icons also need to get bigger here:
grafik

Edit:
Idk if this is a problem on my part but often my team wont get loaded in the sidebar and is jsut empty. This also happens sometimes with enemy trainers

**Comment by Eruyome** [comment]
@sirzento Noted, I'll come around to it. Not sure when.

**Pull request closed without merging**
